### PR TITLE
Add LICENSE file, Yocto needs it.

### PR DESCRIPTION
**Pull request by poussa**
Signed-off-by: Sakari Poussa <sakari.poussa@intel.com>

### CODE REVIEW

**Comment by poussa** [comment]
@gabrielschulhof PTAL. New version of iotivity-node can't be integrated to Ostro (via Yocto) since a license file is needed. It is used in .bb files like

```LIC_FILES_CHKSUM = "file://${WORKDIR}/git/MIT-LICENSE.txt;md5=6b58eb710e76f8b9795f41edf589db99"```

**Comment by mythi** [comment]
@poussa just learnt this while reviewing other PRs: seems it's possible to use something like this in iotivity-node.bb (and thus this PR is not needed):

LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/Apache-2.0;md5=89aea4e17d99a7cacdbeed46a0096b10"

**Comment by gabrielschulhof** [comment]
It is my understanding that the Apache 2.0 license is a per-file license, so it must be appended to each file in the project it is expected to govern. In fact, the text reads in part

> you may not use this file except in compliance with the License.

So, if we put this text in a file that contains nothing else, in that file there is no material over which it would enforce its terms while it would make no statements about the conditions of use of the contents of other files.

@mythi @nagineni can you please confirm that iotivity-node can be built without this PR? If so, we can close it - otherwise we can add something like "The files in this repository are available under the Apache 2.0 license. Please access them individually."

**Comment by mythi** [comment]
On Tue, Mar 8, 2016 at 4:54 PM, gabrielschulhof wrote:

> @mythi <https://github.com/mythi> @nagineni <https://github.com/nagineni>
> can you please confirm that iotivity-node can be built without this PR? If
> so, we can close it - otherwise we can add something like "The files in
> this repository are available under the Apache 2.0 license. Please access
> them individually."
>
>
I'm able to confirm this. Not needed.

**Pull request closed without merging**
