### PR TITLE
join disjunct development branches

### PR DESCRIPTION
**Pull request by pohly**
The "master" branch was reset when starting to work on 1.1.x. Older
1.0.x releases were still available via tags, but not reachable via
the "master" branch anymore. This broke fetching their source code via
bitbake because it violates the sanity check that the specified
revision must be included in the master branch.

In particular, Ostro OS 1.0 is affected by that. Rebuilding it from
source no longer works. To fix this, one could update the released
Ostro OS 1.0. But it is easier to fix this mistake in the
iotivity-node repository: this artificial merge commit joins the two
development branches without changing the content of the current
"master" branch.

I verified that the Ostro OS 1.0 recipe can pull the original source
again when pointing it to my repo with the updated "master" branch.

### CODE REVIEW

**Comment by nagineni** [comment]
I created v1.0.1-1 branch to use it in the Ostro 1.0 directly, but I am fine with merging it into the master.

**Comment by nagineni** [comment]
@poussa

**Comment by poussa** [comment]
So this is just bringing in the history back which was lost at some point? Does not alter the master branch content? And the purpose is to be able to build ostro 1.0 against the commit id which was lost?

If the answer is 'yes' to all three questions than I am OK.

**Comment by pohly** [comment]
@nagineni creating the v1.0.1-1 is not enough for existing recipes (like the one in Ostro OS 1.0) because the commit is expected to be on the master branch.

@poussa yes (well, not entirely lost, but not included in master anymore), yes, and yes.

Proof:
```
iotivity-node$ git log --oneline -n1 
58e3e43 repository: join disjunct development branches
iotivity-node$ git diff origin/master..pohly/master | diffstat
 0 files changed
```

**Comment by gvancuts** [comment]
:+1: following my own testing

**Comment by gabrielschulhof** [comment]
Currently, the master branch in this repo is a clone of gerrit. This means, effectively, that this repo is closed and that gerrit is the destination to which recipes should point. Unfortunately, gerrit does not support importing existing history, which is why I had to interrupt master and reset it to the initial commit from gerrit, and which is why this repo remains open.

If I were to apply this change, the master branch here would once again diverge from the master branch on gerrit - if not in content, then in revision history. This would introduce an undesirable state where the content of the two repos is the same, but the commitids at the tip of master are not. Thus, I am reluctant to merge this.

**Comment by poussa** [comment]
I am with @gabrielschulhof on this one. Merging this would cause major headache for iotivity-node for good. Instead, we should change the Ostro 1.0 recipe to pick up the correct id.

**Comment by pohly** [comment]
Can't you take this PR and also submit it to Gerrit?

**Comment by gabrielschulhof** [comment]
@pohly unfortunately not. gerrit only accepts actual content changes. Any change that refers to commits not in the gerrit repo will not be accepted. Additionally, the commitid containing the submitted changes isn't the commitid that ends up on master. gerrit actually intentionally creates a branch for every change that would go on master and cherry-picks onto master from that branch once the change is approved by reviewers.

**Comment by pohly** [comment]
@gabrielschulhof then someone will have to figure out how to update Ostro OS 1.0. I don't have time for that now.

**Comment by poussa** [comment]
@nagineni can you help on this ?

**Comment by nagineni** [comment]
I don't think I have an access to re-create the existing Ostro OS 1.0 release tag after updating the iotivity-node recipe.

**Comment by gabrielschulhof** [comment]
I think we're now working safely from the new tree. Closing this.

**Pull request closed without merging**
