### PR TITLE
Add API binding : Add OCSetDeviceId into JS layer

### PR DESCRIPTION
**Pull request by Touyote**
* Add the binding
		    * Added a unit test for it
		    * Fixed an include import into build-csdk.js

### CODE REVIEW

**Comment by Touyote** [comment]
Hello @gabrielschulhof,

Sorry again for the delay, I intended to find a way for reproduce the error at 100% unfortunately I can't...
I would also remind you to test it with ubuntu 16.04 on an arm 32/64 & an x86.

**Comment by gabrielschulhof** [comment]
Landed as fe815f5bfe9a3b6e6fd69b39f8efc5ae3630d442 with some changes in branch [1.4.0](https://github.com/intel/iotivity-node/tree/1.4.0). Will release along with 1.4.0.

**Comment by gabrielschulhof** [comment]
Thanks for contributing!

**Comment by Touyote** [comment]
Cool! Thanks for the help too !

**Pull request closed without merging**
