### PR TITLE
All: Update spec version to res.1.1.0 implented in IoTivity 1.2.0

### PR DESCRIPTION
**Pull request by rzr**
Also align data models

Change-Id: I6236546ba8bb93416cbf8cd3ca2555ae3f3935c5
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by wind-rider** [comment]
@rzr @gabrielschulhof is there a reason why this pr is not yet merged (or why I shouldn't use it yet), other than a failing build?

Maybe if you'd rebase it on the current master it would work?

**Comment by gabrielschulhof** [comment]
Sorry! Didn't have a chance to check it out yet.

**Comment by wind-rider** [comment]
Thank you!

**Comment by rzr** [comment]
you welcome, make sure it does not break anything:

I saw those alerts on IRC:

Change view : https://github.com/otcshare/iotivity-node/compare/ab0e6f3ddb98...a4c1fd306851
Build details : https://travis-ci.org/otcshare/iotivity-node/builds/201068030

Change view : https://github.com/gabrielschulhof/iotivity-node/compare/a95974660748...d2a0c160ef21
Build details : https://travis-ci.org/gabrielschulhof/iotivity-node/builds/201101546

Change view : https://github.com/gabrielschulhof/iotivity-node/compare/13cdbaa48c8e...a4c1fd306851
Build details : https://travis-ci.org/gabrielschulhof/iotivity-node/builds/201101557

**Comment by gabrielschulhof** [comment]
Because the tests entail doing actual network communication, sometimes they
fail. Rarely though. I've restarted the two failed jobs.

**Pull request closed without merging**
