### PR TITLE
OicClient: Remove handle when PRESENCE_TRIGGER_DELETE event is received

### PR DESCRIPTION
**Pull request by nagineni**
Delete the handle from the list when the presence is disabled and device has been deleted.

### CODE REVIEW

**Comment by nagineni** [comment]
@gabrielschulhof

**Comment by gabrielschulhof** [comment]
I think a better way would be to ```OCCancel()``` not during `OC_PRESENCE_TRIGGER_DELETE```, but during device addition, because there's a case where you ```device.disablePresence()```, but you don't terminate the process right thereafter. That's the scenario being explored by the failing test. I'll make a test where the server *is* being restarted, to make sure you get the delete event the second time around as well.

**Comment by gabrielschulhof** [comment]
Actually, it's much simpler than that. All you have to do is unconditionally re-issue the open-ended presence request upon rediscovery of a given server, because ```_openEndedRequest()``` does the ```OCCancel()``` for you. IOW, you just remove the if-statement from around the ```_openEndedRequest()``` for presence tracking.

**Comment by nagineni** [comment]
Initially I tested by removing that if condition to solve the issue, but I was not fully sure whether it's okay to remove it or not. Please merge the commit, if you are sure that it will not introduce any regression by removing it.

**Comment by gabrielschulhof** [comment]
OK. I'm relying on the tests to spot regressions, and they're all passing, so I'm assuming that we have no regressions.

**Comment by nagineni** [comment]
Great! :)

**Pull request closed without merging**
